# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

before_all do
  cocoapods
  increment_build_number BUILD_NUMBER
  ipa({
    workspace: "Wikipedia.xcworkspace",
    configuration: "Debug",
    scheme: "MyApp",
  })

  # xctool
end

lane :test do
  snapshot
end

lane :alpha do
  sigh :adhoc
  #deliver :testflight
end

lane :beta do
  sigh :adhoc
  deliver :testflight
end

lane :appstore do
  snapshot
  sigh
  deliver :skip_deploy, :force
  # frameit
end

after_all do |lane|
  # This block is called, only if the executed lane was successful
  # slack({
  #   message: "Successfully deployed new App Update for [App](http://link.com).",
  #   success: true,
  #   channel: 'development'
  # })
end


error do |lane, exception|
  # Something bad happened
end
